#!/usr/bin/env bash
#
# One-command VPS deploy:
#
#   git clone https://github.com/Nuad106404/trading.git && cd trading && ./deploy.sh
#
# First run: generates .env (JWT secrets, VAPID keys, superadmin password),
# then builds and starts MongoDB + API + web with Docker Compose.
# Later runs / updates: git pull && ./deploy.sh   (rebuilds what changed)
#
# Optional overrides (first run only):
#   API_URL=https://api.example.com WEB_URL=https://example.com \
#   SUPERADMIN_USERNAME=boss SUPERADMIN_PASSWORD='S3cret!123' ./deploy.sh
#
set -euo pipefail
cd "$(dirname "$0")"

if ! command -v docker >/dev/null 2>&1; then
  echo "── Docker not found — installing via get.docker.com ──────"
  SUDO=""
  if [ "$(id -u)" -ne 0 ]; then
    if command -v sudo >/dev/null 2>&1; then SUDO="sudo"; else
      echo "✗ Root or sudo is required to install Docker."; exit 1
    fi
  fi
  if command -v curl >/dev/null 2>&1; then
    curl -fsSL https://get.docker.com | $SUDO sh
  elif command -v wget >/dev/null 2>&1; then
    wget -qO- https://get.docker.com | $SUDO sh
  else
    echo "✗ curl or wget is required to download the Docker installer."; exit 1
  fi
  $SUDO systemctl enable --now docker 2>/dev/null || true
  if ! command -v docker >/dev/null 2>&1; then
    echo "✗ Docker installation failed — install manually: https://docs.docker.com/engine/install/"
    exit 1
  fi
  echo "✓ Docker installed."
fi
if ! docker compose version >/dev/null 2>&1; then
  echo "✗ Docker Compose v2 plugin is missing. On Debian/Ubuntu:"
  echo "    apt-get install docker-compose-plugin"
  exit 1
fi

if [ ! -f .env ]; then
  echo "── First run: generating .env ─────────────────────────────"

  IP=$(hostname -I 2>/dev/null | awk '{print $1}')
  IP=${IP:-localhost}
  API_URL=${API_URL:-http://$IP:4000}
  WEB_URL=${WEB_URL:-http://$IP:3000}

  SA_USER=${SUPERADMIN_USERNAME:-sl106404}
  if [ -n "${SUPERADMIN_PASSWORD:-}" ]; then
    SA_PASS="$SUPERADMIN_PASSWORD"
    SA_PASS_GENERATED=0
  else
    SA_PASS="$(openssl rand -base64 12 | tr -dc 'A-Za-z0-9' | head -c 14)aA1"
    SA_PASS_GENERATED=1
  fi

  echo "• Generating VAPID keys for web push (one-off node container)…"
  VAPID_JSON=$(docker run --rm node:22-alpine sh -c "npx -y web-push generate-vapid-keys --json" 2>/dev/null | tail -1)
  VAPID_PUB=$(printf '%s' "$VAPID_JSON" | sed -n 's/.*"publicKey":"\([^"]*\)".*/\1/p')
  VAPID_PRIV=$(printf '%s' "$VAPID_JSON" | sed -n 's/.*"privateKey":"\([^"]*\)".*/\1/p')
  if [ -z "$VAPID_PUB" ]; then
    echo "  (could not generate VAPID keys — push notifications will be disabled; re-run later)"
  fi

  cat > .env <<EOF
# generated by deploy.sh $(date -u +%Y-%m-%dT%H:%M:%SZ) — edit and re-run ./deploy.sh to apply
NEXT_PUBLIC_API_URL=$API_URL
WEB_ORIGIN=$WEB_URL

JWT_ACCESS_SECRET=$(openssl rand -hex 32)
JWT_REFRESH_SECRET=$(openssl rand -hex 32)

SUPERADMIN_USERNAME=$SA_USER
SUPERADMIN_PASSWORD=$SA_PASS
SUPERADMIN_EMAIL=superadmin@local.host

VAPID_PUBLIC_KEY=$VAPID_PUB
VAPID_PRIVATE_KEY=$VAPID_PRIV
VAPID_SUBJECT=mailto:admin@local.host

TRADING_LOSS_ALERT_THRESHOLD=100
EOF
  chmod 600 .env

  echo "• .env written."
  echo
  echo "  Web app  : $WEB_URL"
  echo "  API      : $API_URL"
  echo "  Superadmin login : $SA_USER"
  if [ "$SA_PASS_GENERATED" = "1" ]; then
    echo "  Superadmin password (SAVE THIS): $SA_PASS"
  fi
  echo
fi

# ./deploy.sh --reset-superadmin
# After editing SUPERADMIN_PASSWORD (or _EMAIL) in .env: applies the new env
# to the api container and force re-hashes the protected superadmin's
# credentials — the ONLY sanctioned way to rotate them.
if [ "${1:-}" = "--reset-superadmin" ]; then
  echo "── Re-seeding superadmin credentials from .env ────────────"
  docker compose up -d
  docker compose exec api node dist/seed/reseed --force-reset
  echo "✓ Superadmin credentials now match SUPERADMIN_* in .env"
  exit 0
fi

echo "── Building & starting containers ─────────────────────────"
docker compose up -d --build

echo
echo "✓ Done. Containers:"
docker compose ps --format 'table {{.Name}}\t{{.Status}}\t{{.Ports}}'
echo
echo "Web:  $(grep '^WEB_ORIGIN=' .env | cut -d= -f2-)"
echo "API:  $(grep '^NEXT_PUBLIC_API_URL=' .env | cut -d= -f2-)"
echo "Logs: docker compose logs -f"
